source "https://rubygems.org"

gem "active_model_serializers"
gem "autoprefixer-rails"
gem "coffee-rails", "~> 4.0.0"
gem "ember-rails"
gem "haml-rails"
gem "jquery-rails"
gem "pry"
gem "rails", "4.1.2"
gem "sass-rails", "~> 4.0.3"
gem "sqlite3"
